deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: metakermit
  password:
    secure: ZSHl5Udunnk9X2aS8Y1jLv55QkGbFLARnNONgtVnOKn1cPopjrDwmV/wHsI+r14MnZMDx0YK4vZ4JDbi7w1PTQCoDDFdkhYdveNmI4l2nPWcubal5tKwic6refEKsklbF4cEOIj9+FpQaaGGnVeZD6Km1EhcYLCG/3BF3DE/1CaPi7s0NOAm99Q+YgsNtekrRCYZ1pubyizjhcjPDlPpTv8UhB/IQZM8NK9jEZFeXB8B1Y4Ehld34mCFP4hbcVZSEYJfEp8E3ziCds2QJurP5f3vP2H9Y6/waIxrIMg1ckLa2YDuBAUHfT6JMVhLy1wdPnbSrbMThHRXpHBFAF/x3nK7++bcSlNo6cEBbWGNNszwYXQm6expefT2DC/Vi/X/JIN7gEHfJ72OQUbXY35T53CCDmWxdIcQO9A9b2a/c7ycfYNcwrY+p2VHHjan1Eeupy7p1+wYdFQYv9pMhXm0N5bKhXDZpj/Eljib+5LBk/gy8T1UdSn8BoSeHuAHqXfXc+Sujo4mkRUB7LUaR8fivpgtksGEHXbinxWvh3U1COUXL4k2q7UKAC1Yvye9Sot0drrkwZmo2w3Y9QtkzTNgFFt6EF1AxaTPUlDClIUj3SqgUiXDqS4oQG1uyWTGLX0EMzP0kxSetBDvU3XNowHyDttLVudp0IiWtSQehNP8UNE=
  skip_cleanup: true
  on:
    repo: metakermit/django-spa
    branch: master
    tags: true
  api_key:
    secure: WTIHlDnK4muaI0oHJTbtGIR/Wr8ENQiePS1/vSCx/rnMtbjRPznQsLYW9gw6TYj4ot+h932AP6mnniPGJwF4mL6wTxrAr9y/oRBv5woX+HenXV46ndz3Yqyx4HtxxANxNoWC08+uYE4FndtkQFTsfCuvbqnIQ29xhif5hmM3+qBkCuMx/cQw0CsvXHTGTQCobkkZ0R8yX/h2vloKCkn4JzNn4h9YThyCT8oDjEQaGQjQvwLSItk+gMR65EY1AROTdp6gYigFugg/rLDE9cCaFrhpl8eCRM48m2LsdLutV5wR4Nk/3m38bjvBDtez/6nFwVMrWU/xmscapCVFDEL5EAR4K/pMf4xIrDeQRxLSTuCJzVBTCm4BDY3eXgqJP9h4zfQJLFK/gFVvWxPZ+8TR9oCzH7SvWN8QBrPrhbLzwjNrwR58Q6WjyyBeYsJ6GPlTH2T7YU2H2BqByw3wep8j0TkgoGhYwIrbOCKQqzald8gfWg1U5KY7IGh5csdDznL4PaHSa8JR4+qyr6VZ6LmEIEAa7AS56D8pM9nJz2edVXLBkjsPuvKr7seInY+o6BET5xiIlPkt28J5rBXP3fShg1fnrJxC0ulLvp6sra26ZeA3ajJBmck1jSLM3GdETX1SUdH85lh6glZKoKtwn7lHVqjChGyHG37MX7m1NJB3QMc=
install:
- pip install pipenv
- pipenv install
language: python
python: 3.7
script:
- pipenv run pytest
