deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: aZnw6Fhv0ro6fp1v3/90UT1q/AeTl93xVOCcg1hShmoJsqKCQPVI5CjeeE+Nh1hyXvytUNWz7nHLH4uqCLLlorQIUaDNUZflBLj9y4GoFDQOL+PXdTgP68etRelj+1Ar2qVpJGd8hACHMZZAU1xFQV7JpweSBS9c+AaPAxtfRpJUkLI+i82Hh3mIJPmnlfP4GSVTt4NIC+0ymv4TlCa/HAijMfjyvZDRmW18+id3q5SrQ/1WznOpQrHJCKdHFsO/w8wmBNxlbd9Iz0eboQfEPzjqZHUpihC/nV6i9j0UyjygnmJ+fGbyYAZyWkj67goVaDv0gpMK6TSO+k472Gl/9tcMs2g11dIQ8as1vrXxoCxsWvJFxoNzcGGTUQhYMBrRZGMdtRi6TmhuaOJS8kx1WbvHP9CN6+XAtg1ttIzaalfuNWw0KjXjpv9E/W+CXula5g1n16aJbt8K8pLpQixwMivZBaomvKJTrvjbW+AKGDpn+sE3tiB7zEnrz8a223hdub39tcc1vbILXlNfM0+GUXaL1XD0YbG1oryrcLvbJnMP0eT4jlif01I7trkWgneiDCvYK9Sr5rnhi625NxGWys51Uah3x4lASs4iCbLvBpIdtD+2yzsdj6p3vHG7pDWdjXapjz0ZiBTMYImJvEdJWbrAZtJtGX28TY6VBEIq5Zo=
  skip_cleanup: true
  on:
    repo: metakermit/django-spa
    branch: master
    tags: true
  api_key:
    secure: WTIHlDnK4muaI0oHJTbtGIR/Wr8ENQiePS1/vSCx/rnMtbjRPznQsLYW9gw6TYj4ot+h932AP6mnniPGJwF4mL6wTxrAr9y/oRBv5woX+HenXV46ndz3Yqyx4HtxxANxNoWC08+uYE4FndtkQFTsfCuvbqnIQ29xhif5hmM3+qBkCuMx/cQw0CsvXHTGTQCobkkZ0R8yX/h2vloKCkn4JzNn4h9YThyCT8oDjEQaGQjQvwLSItk+gMR65EY1AROTdp6gYigFugg/rLDE9cCaFrhpl8eCRM48m2LsdLutV5wR4Nk/3m38bjvBDtez/6nFwVMrWU/xmscapCVFDEL5EAR4K/pMf4xIrDeQRxLSTuCJzVBTCm4BDY3eXgqJP9h4zfQJLFK/gFVvWxPZ+8TR9oCzH7SvWN8QBrPrhbLzwjNrwR58Q6WjyyBeYsJ6GPlTH2T7YU2H2BqByw3wep8j0TkgoGhYwIrbOCKQqzald8gfWg1U5KY7IGh5csdDznL4PaHSa8JR4+qyr6VZ6LmEIEAa7AS56D8pM9nJz2edVXLBkjsPuvKr7seInY+o6BET5xiIlPkt28J5rBXP3fShg1fnrJxC0ulLvp6sra26ZeA3ajJBmck1jSLM3GdETX1SUdH85lh6glZKoKtwn7lHVqjChGyHG37MX7m1NJB3QMc=
install:
- pip install pipenv
- pipenv install
language: python
python: 3.7
script:
- pipenv run pytest
